[target.'cfg(all(target_arch = "arm", target_os = "none"))']
# we need probe-run to run target tests
# note: this will be overridden by the top-level config.toml
runner = "probe-rs run --chip RP2040"

rustflags = [
  "-C", "link-arg=-Tdefmt.x",
]

[build]
target = "thumbv6m-none-eabi"

[env]
DEFMT_LOG = "trace"
