on: [push, pull_request]
name: Clippy check
jobs:
  clippy_check:
    name: Run Clippy
    runs-on: ubuntu-20.04
    env:
      RUSTFLAGS: "-D warnings"
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          target: thumbv6m-none-eabi
          components: clippy
      - name: Build rp2040-hal
        run: cd rp2040-hal && cargo clippy --target=thumbv6m-none-eabi
      - name: Build rp2040-hal (with all features)
        run: cd rp2040-hal && cargo clippy --target=thumbv6m-none-eabi --all-features
      - name: Build rp2040-hal-macros
        run: cd rp2040-hal-macros && cargo clippy 
      - name: Build on-target-tests
        run: cd on-target-tests && cargo clippy 
      - name: Build rp2040-hal-examples
        run: cd rp2040-hal-examples && cargo clippy 
      - name: Build rp-binary-info
        run: cd rp-binary-info && cargo clippy 
