on: [push, pull_request]
name: Check rp235x-hal-examples on RISC-V
env:
  PACKAGE: rp235x-hal-examples
  TARGET: riscv32imac-unknown-none-elf
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          target: ${{ env.TARGET }}
      - name: Build
        run: |
          cd ${PACKAGE}
          cat riscv_examples.txt | while read example; do
            echo "Building $example"
            cargo build --target=${TARGET} --bin $example
          done
  msrv:
    name: Verify build on MSRV
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.79
          target: ${{ env.TARGET }}
      - name: Use older version of regex
        run: cd ${PACKAGE} && cargo update -p regex --precise 1.9.3
      - name: Build on MSRV
        run: |
          cd ${PACKAGE}
          cat riscv_examples.txt | while read example; do
            echo "Building $example"
            cargo build --target=${TARGET} --bin $example
          done
  fmt:
    runs-on: ubuntu-24.04
    env:
      RUSTFLAGS: "-D warnings"
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - name: Check format
        run: cd ${PACKAGE} && cargo fmt -- --check
  clippy:
    runs-on: ubuntu-24.04
    env:
      RUSTFLAGS: "-D warnings"
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          target: ${{ env.TARGET }}
          components: clippy
      - name: Run cargo clippy
        run: |
          cd ${PACKAGE}
          cat riscv_examples.txt | while read example; do
            echo "Checking $example"
            cargo clippy --target=${TARGET} --bin $example
          done
