on: [push, pull_request]
name: Check rp-hal-common
env:
  PACKAGE: rp-hal-common
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Install cargo-hack
        run: |
          curl -sSL https://github.com/taiki-e/cargo-hack/releases/download/v0.6.17/cargo-hack-x86_64-unknown-linux-gnu.tar.gz | tar xvzf - -C ~/.cargo/bin
      - name: Build
        run: cd ${PACKAGE} && cargo hack build --optional-deps --each-feature
  test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Install cargo-hack
        run: |
          curl -sSL https://github.com/taiki-e/cargo-hack/releases/download/v0.6.17/cargo-hack-x86_64-unknown-linux-gnu.tar.gz | tar xvzf - -C ~/.cargo/bin
      - name: Test
        run: cd ${PACKAGE} && cargo hack test --optional-deps --each-feature --tests
      - name: Test docs
        run: cd ${PACKAGE} && cargo hack test --optional-deps --each-feature --doc
  udeps:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2025-02-28
      - name: Install cargo-hack
        run: |
          curl -sSL https://github.com/taiki-e/cargo-hack/releases/download/v0.6.17/cargo-hack-x86_64-unknown-linux-gnu.tar.gz | tar xvzf - -C ~/.cargo/bin
      - name: Install cargo-udeps
        run: |
          curl -sSL https://github.com/est31/cargo-udeps/releases/download/v0.1.55/cargo-udeps-v0.1.55-x86_64-unknown-linux-gnu.tar.gz | tar xvzf - --strip-components=2 -C ~/.cargo/bin ./cargo-udeps-v0.1.55-x86_64-unknown-linux-gnu/cargo-udeps
      - name: Run cargo-udeps
        run: cd ${PACKAGE} && cargo hack udeps --optional-deps --each-feature
  msrv:
    name: Verify build on MSRV
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.79
      - name: Install cargo-hack
        run: |
          curl -sSL https://github.com/taiki-e/cargo-hack/releases/download/v0.6.17/cargo-hack-x86_64-unknown-linux-gnu.tar.gz | tar xvzf - -C ~/.cargo/bin
      - name: Build on MSRV
        run: cd ${PACKAGE} && cargo hack build --optional-deps --each-feature
  fmt:
    runs-on: ubuntu-24.04
    env:
      RUSTFLAGS: "-D warnings"
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - name: Check format
        run: cd ${PACKAGE} && cargo fmt -- --check
  clippy:
    runs-on: ubuntu-24.04
    env:
      RUSTFLAGS: "-D warnings"
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - name: Run cargo clippy
        run: cd ${PACKAGE} && cargo clippy
